// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ml_dsa_87_from_entropy`, `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

void setDefaultSs58Prefix({required int prefix}) =>
    RustLib.instance.api.crateApiCryptoSetDefaultSs58Prefix(prefix: prefix);

/// Convert public key to accountId32 in ss58check format
String toAccountId({required Keypair obj}) => RustLib.instance.api.crateApiCryptoToAccountId(obj: obj);

/// Convert key in ss58check format to accountId32
Uint8List ss58ToAccountId({required String s}) => RustLib.instance.api.crateApiCryptoSs58ToAccountId(s: s);

/// Legacy non-HD ML-DSA-87 keypair straight from the mnemonic seed (early CLI and miner accounts).
Keypair generateKeypair({required String mnemonicStr}) =>
    RustLib.instance.api.crateApiCryptoGenerateKeypair(mnemonicStr: mnemonicStr);

Keypair generateDerivedKeypair({required String mnemonicStr, required String path, required DilithiumScheme scheme}) =>
    RustLib.instance.api.crateApiCryptoGenerateDerivedKeypair(mnemonicStr: mnemonicStr, path: path, scheme: scheme);

WormholeResult deriveWormhole({required String mnemonicStr, required String path}) =>
    RustLib.instance.api.crateApiCryptoDeriveWormhole(mnemonicStr: mnemonicStr, path: path);

/// Convert a first_hash (rewards preimage) to its corresponding wormhole address.
///
/// Mirrors how the chain and ZK circuit derive the address from the preimage:
/// - Convert 32 bytes → 4 Poseidon field elements (8 bytes each)
/// - Hash once without padding
String firstHashToAddress({required String firstHashHex}) =>
    RustLib.instance.api.crateApiCryptoFirstHashToAddress(firstHashHex: firstHashHex);

/// ML-DSA-87 keypair from a raw 32-byte seed (dev accounts).
Keypair generateKeypairFromSeed({required List<int> seed}) =>
    RustLib.instance.api.crateApiCryptoGenerateKeypairFromSeed(seed: seed);

/// Signs `message`. Spec 148+ uses [`signing_context::EXTRINSIC`]; earlier specs use none.
Uint8List signMessage({
  required Keypair keypair,
  required List<int> message,
  U8Array32? entropy,
  required int specVersion,
}) => RustLib.instance.api.crateApiCryptoSignMessage(
  keypair: keypair,
  message: message,
  entropy: entropy,
  specVersion: specVersion,
);

Uint8List signMessageWithPubkey({
  required Keypair keypair,
  required List<int> message,
  U8Array32? entropy,
  required int specVersion,
}) => RustLib.instance.api.crateApiCryptoSignMessageWithPubkey(
  keypair: keypair,
  message: message,
  entropy: entropy,
  specVersion: specVersion,
);

/// Verifies under the same context [`sign_message`] would use for `spec_version`.
bool verifyMessage({
  required Keypair keypair,
  required List<int> message,
  required List<int> signature,
  required int specVersion,
}) => RustLib.instance.api.crateApiCryptoVerifyMessage(
  keypair: keypair,
  message: message,
  signature: signature,
  specVersion: specVersion,
);

Keypair crystalAlice() => RustLib.instance.api.crateApiCryptoCrystalAlice();

Keypair crystalBob() => RustLib.instance.api.crateApiCryptoCrystalBob();

Keypair crystalCharlie() => RustLib.instance.api.crateApiCryptoCrystalCharlie();

int publicKeyBytes({required DilithiumScheme scheme}) =>
    RustLib.instance.api.crateApiCryptoPublicKeyBytes(scheme: scheme);

int secretKeyBytes({required DilithiumScheme scheme}) =>
    RustLib.instance.api.crateApiCryptoSecretKeyBytes(scheme: scheme);

int signatureBytes({required DilithiumScheme scheme}) =>
    RustLib.instance.api.crateApiCryptoSignatureBytes(scheme: scheme);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HDLatticeError>>
abstract class HdLatticeError implements RustOpaqueInterface {}

/// ML-DSA parameter set of a keypair. Mirrors quantus-cli's `DilithiumScheme`;
/// accounts stored before this existed are ML-DSA-87.
enum DilithiumScheme { mlDsa65, mlDsa87 }

class Keypair {
  final Uint8List publicKey;
  final Uint8List secretKey;
  final DilithiumScheme scheme;

  const Keypair({required this.publicKey, required this.secretKey, required this.scheme});

  @override
  int get hashCode => publicKey.hashCode ^ secretKey.hashCode ^ scheme.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Keypair &&
          runtimeType == other.runtimeType &&
          publicKey == other.publicKey &&
          secretKey == other.secretKey &&
          scheme == other.scheme;
}

class U8Array32 extends NonGrowableListView<int> {
  static const arraySize = 32;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array32(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U8Array32.init() : this(Uint8List(arraySize));
}

class WormholeResult {
  final String address;
  final Uint8List firstHash;
  final Uint8List secret;

  const WormholeResult({required this.address, required this.firstHash, required this.secret});

  @override
  int get hashCode => address.hashCode ^ firstHash.hashCode ^ secret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WormholeResult &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          firstHash == other.firstHash &&
          secret == other.secret;
}
