// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `derive_multisig_address`

/// Predicts the on-chain multisig address for the given signers, threshold, and nonce.
///
/// Address is computed as: hash(pallet_id || sorted_signers || threshold || nonce)
String predictMultisigAddress({required List<String> signers, required int threshold, required BigInt nonce}) =>
    RustLib.instance.api.crateApiMultisigPredictMultisigAddress(signers: signers, threshold: threshold, nonce: nonce);
