// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `within_limits`

int maxUrParts() => RustLib.instance.api.crateApiUrMaxUrParts();

int maxUrPartChars() => RustLib.instance.api.crateApiUrMaxUrPartChars();

Uint8List decodeUr({required List<String> urParts}) => RustLib.instance.api.crateApiUrDecodeUr(urParts: urParts);

List<String> encodeUr({required List<int> data, int? maxFragmentLength}) =>
    RustLib.instance.api.crateApiUrEncodeUr(data: data, maxFragmentLength: maxFragmentLength);

bool isCompleteUr({required List<String> urParts}) => RustLib.instance.api.crateApiUrIsCompleteUr(urParts: urParts);
