// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/crypto.dart';
import 'api/multisig.dart';
import 'api/ur.dart';
import 'api/wormhole.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiCryptoInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1684949517;

  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
    stem: 'rust_lib_quantus_wallet',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<Uint8List> crateApiWormholeAggregateProofs({required List<Uint8List> proofBytesList, required String binsDir});

  String crateApiWormholeComputeAddressHashHex({required List<int> rawAddress});

  MerkleProcessed crateApiWormholeComputeMerklePositions({
    required List<int> unsortedSiblingsFlat,
    required List<int> leafHash,
    required int depth,
  });

  Uint8List crateApiWormholeComputeNullifier({required List<int> secret, required BigInt transferCount});

  Uint8List crateApiWormholeComputeWormholeAddress({required List<int> secret});

  Keypair crateApiCryptoCrystalAlice();

  Keypair crateApiCryptoCrystalBob();

  Keypair crateApiCryptoCrystalCharlie();

  int crateApiWormholeDecodeLeafAmount({required List<int> leafData});

  Uint8List crateApiWormholeDecodeLeafToAccount({required List<int> leafData});

  BigInt crateApiWormholeDecodeLeafTransferCount({required List<int> leafData});

  Uint8List crateApiUrDecodeUr({required List<String> urParts});

  WormholeResult crateApiCryptoDeriveWormhole({required String mnemonicStr, required String path});

  List<String> crateApiUrEncodeUr({required List<int> data, int? maxFragmentLength});

  Future<String> crateApiWormholeEnsureCircuitBinaries({required String binsDir});

  String crateApiCryptoFirstHashToAddress({required String firstHashHex});

  Keypair crateApiCryptoGenerateDerivedKeypair({
    required String mnemonicStr,
    required String path,
    required DilithiumScheme scheme,
  });

  Keypair crateApiCryptoGenerateKeypair({required String mnemonicStr});

  Keypair crateApiCryptoGenerateKeypairFromSeed({required List<int> seed});

  Future<ProofOutput> crateApiWormholeGenerateProof({
    required ProofInput input,
    required String proverBinPath,
    required String commonBinPath,
  });

  Future<void> crateApiCryptoInitApp();

  bool crateApiUrIsCompleteUr({required List<String> urParts});

  int crateApiUrMaxUrPartChars();

  int crateApiUrMaxUrParts();

  String crateApiMultisigPredictMultisigAddress({
    required List<String> signers,
    required int threshold,
    required BigInt nonce,
  });

  int crateApiCryptoPublicKeyBytes({required DilithiumScheme scheme});

  int crateApiCryptoSecretKeyBytes({required DilithiumScheme scheme});

  void crateApiCryptoSetDefaultSs58Prefix({required int prefix});

  Uint8List crateApiCryptoSignMessage({
    required Keypair keypair,
    required List<int> message,
    U8Array32? entropy,
    required int specVersion,
  });

  Uint8List crateApiCryptoSignMessageWithPubkey({
    required Keypair keypair,
    required List<int> message,
    U8Array32? entropy,
    required int specVersion,
  });

  int crateApiCryptoSignatureBytes({required DilithiumScheme scheme});

  Uint8List crateApiCryptoSs58ToAccountId({required String s});

  String crateApiCryptoToAccountId({required Keypair obj});

  bool crateApiCryptoVerifyMessage({
    required Keypair keypair,
    required List<int> message,
    required List<int> signature,
    required int specVersion,
  });

  int crateApiWormholeWormholeComputeOutputAmount({required int inputAmount, required int feeBps});

  String crateApiWormholeZkCircuitsVersion();

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_HdLatticeError;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_HdLatticeError;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_HdLatticeErrorPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Uint8List> crateApiWormholeAggregateProofs({
    required List<Uint8List> proofBytesList,
    required String binsDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_list_prim_u_8_strict(proofBytesList, serializer);
          sse_encode_String(binsDir, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_prim_u_8_strict, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiWormholeAggregateProofsConstMeta,
        argValues: [proofBytesList, binsDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWormholeAggregateProofsConstMeta =>
      const TaskConstMeta(debugName: 'aggregate_proofs', argNames: ['proofBytesList', 'binsDir']);

  @override
  String crateApiWormholeComputeAddressHashHex({required List<int> rawAddress}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(rawAddress, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiWormholeComputeAddressHashHexConstMeta,
        argValues: [rawAddress],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWormholeComputeAddressHashHexConstMeta =>
      const TaskConstMeta(debugName: 'compute_address_hash_hex', argNames: ['rawAddress']);

  @override
  MerkleProcessed crateApiWormholeComputeMerklePositions({
    required List<int> unsortedSiblingsFlat,
    required List<int> leafHash,
    required int depth,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(unsortedSiblingsFlat, serializer);
          sse_encode_list_prim_u_8_loose(leafHash, serializer);
          sse_encode_u_32(depth, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_merkle_processed, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiWormholeComputeMerklePositionsConstMeta,
        argValues: [unsortedSiblingsFlat, leafHash, depth],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWormholeComputeMerklePositionsConstMeta => const TaskConstMeta(
    debugName: 'compute_merkle_positions',
    argNames: ['unsortedSiblingsFlat', 'leafHash', 'depth'],
  );

  @override
  Uint8List crateApiWormholeComputeNullifier({required List<int> secret, required BigInt transferCount}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(secret, serializer);
          sse_encode_u_64(transferCount, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_prim_u_8_strict, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiWormholeComputeNullifierConstMeta,
        argValues: [secret, transferCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWormholeComputeNullifierConstMeta =>
      const TaskConstMeta(debugName: 'compute_nullifier', argNames: ['secret', 'transferCount']);

  @override
  Uint8List crateApiWormholeComputeWormholeAddress({required List<int> secret}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(secret, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_prim_u_8_strict, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiWormholeComputeWormholeAddressConstMeta,
        argValues: [secret],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWormholeComputeWormholeAddressConstMeta =>
      const TaskConstMeta(debugName: 'compute_wormhole_address', argNames: ['secret']);

  @override
  Keypair crateApiCryptoCrystalAlice() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_keypair, decodeErrorData: null),
        constMeta: kCrateApiCryptoCrystalAliceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoCrystalAliceConstMeta =>
      const TaskConstMeta(debugName: 'crystal_alice', argNames: []);

  @override
  Keypair crateApiCryptoCrystalBob() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_keypair, decodeErrorData: null),
        constMeta: kCrateApiCryptoCrystalBobConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoCrystalBobConstMeta => const TaskConstMeta(debugName: 'crystal_bob', argNames: []);

  @override
  Keypair crateApiCryptoCrystalCharlie() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_keypair, decodeErrorData: null),
        constMeta: kCrateApiCryptoCrystalCharlieConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoCrystalCharlieConstMeta =>
      const TaskConstMeta(debugName: 'crystal_charlie', argNames: []);

  @override
  int crateApiWormholeDecodeLeafAmount({required List<int> leafData}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(leafData, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_u_32, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiWormholeDecodeLeafAmountConstMeta,
        argValues: [leafData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWormholeDecodeLeafAmountConstMeta =>
      const TaskConstMeta(debugName: 'decode_leaf_amount', argNames: ['leafData']);

  @override
  Uint8List crateApiWormholeDecodeLeafToAccount({required List<int> leafData}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(leafData, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_prim_u_8_strict, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiWormholeDecodeLeafToAccountConstMeta,
        argValues: [leafData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWormholeDecodeLeafToAccountConstMeta =>
      const TaskConstMeta(debugName: 'decode_leaf_to_account', argNames: ['leafData']);

  @override
  BigInt crateApiWormholeDecodeLeafTransferCount({required List<int> leafData}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(leafData, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_u_64, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiWormholeDecodeLeafTransferCountConstMeta,
        argValues: [leafData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWormholeDecodeLeafTransferCountConstMeta =>
      const TaskConstMeta(debugName: 'decode_leaf_transfer_count', argNames: ['leafData']);

  @override
  Uint8List crateApiUrDecodeUr({required List<String> urParts}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(urParts, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_prim_u_8_strict, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiUrDecodeUrConstMeta,
        argValues: [urParts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUrDecodeUrConstMeta => const TaskConstMeta(debugName: 'decode_ur', argNames: ['urParts']);

  @override
  WormholeResult crateApiCryptoDeriveWormhole({required String mnemonicStr, required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonicStr, serializer);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wormhole_result,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError,
        ),
        constMeta: kCrateApiCryptoDeriveWormholeConstMeta,
        argValues: [mnemonicStr, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoDeriveWormholeConstMeta =>
      const TaskConstMeta(debugName: 'derive_wormhole', argNames: ['mnemonicStr', 'path']);

  @override
  List<String> crateApiUrEncodeUr({required List<int> data, int? maxFragmentLength}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_opt_box_autoadd_u_32(maxFragmentLength, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiUrEncodeUrConstMeta,
        argValues: [data, maxFragmentLength],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUrEncodeUrConstMeta =>
      const TaskConstMeta(debugName: 'encode_ur', argNames: ['data', 'maxFragmentLength']);

  @override
  Future<String> crateApiWormholeEnsureCircuitBinaries({required String binsDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(binsDir, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiWormholeEnsureCircuitBinariesConstMeta,
        argValues: [binsDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWormholeEnsureCircuitBinariesConstMeta =>
      const TaskConstMeta(debugName: 'ensure_circuit_binaries', argNames: ['binsDir']);

  @override
  String crateApiCryptoFirstHashToAddress({required String firstHashHex}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(firstHashHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiCryptoFirstHashToAddressConstMeta,
        argValues: [firstHashHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoFirstHashToAddressConstMeta =>
      const TaskConstMeta(debugName: 'first_hash_to_address', argNames: ['firstHashHex']);

  @override
  Keypair crateApiCryptoGenerateDerivedKeypair({
    required String mnemonicStr,
    required String path,
    required DilithiumScheme scheme,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonicStr, serializer);
          sse_encode_String(path, serializer);
          sse_encode_dilithium_scheme(scheme, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_keypair,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError,
        ),
        constMeta: kCrateApiCryptoGenerateDerivedKeypairConstMeta,
        argValues: [mnemonicStr, path, scheme],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoGenerateDerivedKeypairConstMeta =>
      const TaskConstMeta(debugName: 'generate_derived_keypair', argNames: ['mnemonicStr', 'path', 'scheme']);

  @override
  Keypair crateApiCryptoGenerateKeypair({required String mnemonicStr}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonicStr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_keypair,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError,
        ),
        constMeta: kCrateApiCryptoGenerateKeypairConstMeta,
        argValues: [mnemonicStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoGenerateKeypairConstMeta =>
      const TaskConstMeta(debugName: 'generate_keypair', argNames: ['mnemonicStr']);

  @override
  Keypair crateApiCryptoGenerateKeypairFromSeed({required List<int> seed}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(seed, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_keypair, decodeErrorData: null),
        constMeta: kCrateApiCryptoGenerateKeypairFromSeedConstMeta,
        argValues: [seed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoGenerateKeypairFromSeedConstMeta =>
      const TaskConstMeta(debugName: 'generate_keypair_from_seed', argNames: ['seed']);

  @override
  Future<ProofOutput> crateApiWormholeGenerateProof({
    required ProofInput input,
    required String proverBinPath,
    required String commonBinPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_proof_input(input, serializer);
          sse_encode_String(proverBinPath, serializer);
          sse_encode_String(commonBinPath, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_proof_output, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiWormholeGenerateProofConstMeta,
        argValues: [input, proverBinPath, commonBinPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWormholeGenerateProofConstMeta =>
      const TaskConstMeta(debugName: 'generate_proof', argNames: ['input', 'proverBinPath', 'commonBinPath']);

  @override
  Future<void> crateApiCryptoInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_unit, decodeErrorData: null),
        constMeta: kCrateApiCryptoInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoInitAppConstMeta => const TaskConstMeta(debugName: 'init_app', argNames: []);

  @override
  bool crateApiUrIsCompleteUr({required List<String> urParts}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(urParts, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_bool, decodeErrorData: null),
        constMeta: kCrateApiUrIsCompleteUrConstMeta,
        argValues: [urParts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUrIsCompleteUrConstMeta =>
      const TaskConstMeta(debugName: 'is_complete_ur', argNames: ['urParts']);

  @override
  int crateApiUrMaxUrPartChars() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_u_32, decodeErrorData: null),
        constMeta: kCrateApiUrMaxUrPartCharsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUrMaxUrPartCharsConstMeta =>
      const TaskConstMeta(debugName: 'max_ur_part_chars', argNames: []);

  @override
  int crateApiUrMaxUrParts() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_u_32, decodeErrorData: null),
        constMeta: kCrateApiUrMaxUrPartsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUrMaxUrPartsConstMeta => const TaskConstMeta(debugName: 'max_ur_parts', argNames: []);

  @override
  String crateApiMultisigPredictMultisigAddress({
    required List<String> signers,
    required int threshold,
    required BigInt nonce,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(signers, serializer);
          sse_encode_u_32(threshold, serializer);
          sse_encode_u_64(nonce, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiMultisigPredictMultisigAddressConstMeta,
        argValues: [signers, threshold, nonce],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMultisigPredictMultisigAddressConstMeta =>
      const TaskConstMeta(debugName: 'predict_multisig_address', argNames: ['signers', 'threshold', 'nonce']);

  @override
  int crateApiCryptoPublicKeyBytes({required DilithiumScheme scheme}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_dilithium_scheme(scheme, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_u_32, decodeErrorData: null),
        constMeta: kCrateApiCryptoPublicKeyBytesConstMeta,
        argValues: [scheme],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPublicKeyBytesConstMeta =>
      const TaskConstMeta(debugName: 'public_key_bytes', argNames: ['scheme']);

  @override
  int crateApiCryptoSecretKeyBytes({required DilithiumScheme scheme}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_dilithium_scheme(scheme, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_u_32, decodeErrorData: null),
        constMeta: kCrateApiCryptoSecretKeyBytesConstMeta,
        argValues: [scheme],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoSecretKeyBytesConstMeta =>
      const TaskConstMeta(debugName: 'secret_key_bytes', argNames: ['scheme']);

  @override
  void crateApiCryptoSetDefaultSs58Prefix({required int prefix}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(prefix, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_unit, decodeErrorData: null),
        constMeta: kCrateApiCryptoSetDefaultSs58PrefixConstMeta,
        argValues: [prefix],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoSetDefaultSs58PrefixConstMeta =>
      const TaskConstMeta(debugName: 'set_default_ss58_prefix', argNames: ['prefix']);

  @override
  Uint8List crateApiCryptoSignMessage({
    required Keypair keypair,
    required List<int> message,
    U8Array32? entropy,
    required int specVersion,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_keypair(keypair, serializer);
          sse_encode_list_prim_u_8_loose(message, serializer);
          sse_encode_opt_u_8_array_32(entropy, serializer);
          sse_encode_u_32(specVersion, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_prim_u_8_strict, decodeErrorData: null),
        constMeta: kCrateApiCryptoSignMessageConstMeta,
        argValues: [keypair, message, entropy, specVersion],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoSignMessageConstMeta =>
      const TaskConstMeta(debugName: 'sign_message', argNames: ['keypair', 'message', 'entropy', 'specVersion']);

  @override
  Uint8List crateApiCryptoSignMessageWithPubkey({
    required Keypair keypair,
    required List<int> message,
    U8Array32? entropy,
    required int specVersion,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_keypair(keypair, serializer);
          sse_encode_list_prim_u_8_loose(message, serializer);
          sse_encode_opt_u_8_array_32(entropy, serializer);
          sse_encode_u_32(specVersion, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_prim_u_8_strict, decodeErrorData: null),
        constMeta: kCrateApiCryptoSignMessageWithPubkeyConstMeta,
        argValues: [keypair, message, entropy, specVersion],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoSignMessageWithPubkeyConstMeta => const TaskConstMeta(
    debugName: 'sign_message_with_pubkey',
    argNames: ['keypair', 'message', 'entropy', 'specVersion'],
  );

  @override
  int crateApiCryptoSignatureBytes({required DilithiumScheme scheme}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_dilithium_scheme(scheme, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_u_32, decodeErrorData: null),
        constMeta: kCrateApiCryptoSignatureBytesConstMeta,
        argValues: [scheme],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoSignatureBytesConstMeta =>
      const TaskConstMeta(debugName: 'signature_bytes', argNames: ['scheme']);

  @override
  Uint8List crateApiCryptoSs58ToAccountId({required String s}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(s, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_prim_u_8_strict, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiCryptoSs58ToAccountIdConstMeta,
        argValues: [s],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoSs58ToAccountIdConstMeta =>
      const TaskConstMeta(debugName: 'ss58_to_account_id', argNames: ['s']);

  @override
  String crateApiCryptoToAccountId({required Keypair obj}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_keypair(obj, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: null),
        constMeta: kCrateApiCryptoToAccountIdConstMeta,
        argValues: [obj],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoToAccountIdConstMeta =>
      const TaskConstMeta(debugName: 'to_account_id', argNames: ['obj']);

  @override
  bool crateApiCryptoVerifyMessage({
    required Keypair keypair,
    required List<int> message,
    required List<int> signature,
    required int specVersion,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_keypair(keypair, serializer);
          sse_encode_list_prim_u_8_loose(message, serializer);
          sse_encode_list_prim_u_8_loose(signature, serializer);
          sse_encode_u_32(specVersion, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_bool, decodeErrorData: null),
        constMeta: kCrateApiCryptoVerifyMessageConstMeta,
        argValues: [keypair, message, signature, specVersion],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoVerifyMessageConstMeta =>
      const TaskConstMeta(debugName: 'verify_message', argNames: ['keypair', 'message', 'signature', 'specVersion']);

  @override
  int crateApiWormholeWormholeComputeOutputAmount({required int inputAmount, required int feeBps}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(inputAmount, serializer);
          sse_encode_u_32(feeBps, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 35)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_u_32, decodeErrorData: sse_decode_String),
        constMeta: kCrateApiWormholeWormholeComputeOutputAmountConstMeta,
        argValues: [inputAmount, feeBps],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWormholeWormholeComputeOutputAmountConstMeta =>
      const TaskConstMeta(debugName: 'wormhole_compute_output_amount', argNames: ['inputAmount', 'feeBps']);

  @override
  String crateApiWormholeZkCircuitsVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: null),
        constMeta: kCrateApiWormholeZkCircuitsVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWormholeZkCircuitsVersionConstMeta =>
      const TaskConstMeta(debugName: 'zk_circuits_version', argNames: []);

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_HdLatticeError =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_HdLatticeError =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError;

  @protected
  HdLatticeError dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HdLatticeErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  HdLatticeError dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HdLatticeErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Keypair dco_decode_box_autoadd_keypair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_keypair(raw);
  }

  @protected
  ProofInput dco_decode_box_autoadd_proof_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_proof_input(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  DilithiumScheme dco_decode_dilithium_scheme(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DilithiumScheme.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Keypair dco_decode_keypair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Keypair(
      publicKey: dco_decode_list_prim_u_8_strict(arr[0]),
      secretKey: dco_decode_list_prim_u_8_strict(arr[1]),
      scheme: dco_decode_dilithium_scheme(arr[2]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MerkleProcessed dco_decode_merkle_processed(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MerkleProcessed(
      sortedSiblingsFlat: dco_decode_list_prim_u_8_strict(arr[0]),
      positions: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  U8Array32? dco_decode_opt_u_8_array_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_u_8_array_32(raw);
  }

  @protected
  ProofInput dco_decode_proof_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 19) throw Exception('unexpected arr length: expect 19 but see ${arr.length}');
    return ProofInput(
      secret: dco_decode_list_prim_u_8_strict(arr[0]),
      transferCount: dco_decode_u_64(arr[1]),
      wormholeAddress: dco_decode_list_prim_u_8_strict(arr[2]),
      inputAmount: dco_decode_u_32(arr[3]),
      blockHash: dco_decode_list_prim_u_8_strict(arr[4]),
      blockNumber: dco_decode_u_32(arr[5]),
      parentHash: dco_decode_list_prim_u_8_strict(arr[6]),
      stateRoot: dco_decode_list_prim_u_8_strict(arr[7]),
      extrinsicsRoot: dco_decode_list_prim_u_8_strict(arr[8]),
      digest: dco_decode_list_prim_u_8_strict(arr[9]),
      zkTreeRoot: dco_decode_list_prim_u_8_strict(arr[10]),
      sortedSiblingsFlat: dco_decode_list_prim_u_8_strict(arr[11]),
      positions: dco_decode_list_prim_u_8_strict(arr[12]),
      exitAccount1: dco_decode_list_prim_u_8_strict(arr[13]),
      outputAmount1: dco_decode_u_32(arr[14]),
      exitAccount2: dco_decode_list_prim_u_8_strict(arr[15]),
      outputAmount2: dco_decode_u_32(arr[16]),
      volumeFeeBps: dco_decode_u_32(arr[17]),
      assetId: dco_decode_u_32(arr[18]),
    );
  }

  @protected
  ProofOutput dco_decode_proof_output(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ProofOutput(
      proofBytes: dco_decode_list_prim_u_8_strict(arr[0]),
      nullifier: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  U8Array32 dco_decode_u_8_array_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array32(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WormholeResult dco_decode_wormhole_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return WormholeResult(
      address: dco_decode_String(arr[0]),
      firstHash: dco_decode_list_prim_u_8_strict(arr[1]),
      secret: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  HdLatticeError sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HdLatticeErrorImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  HdLatticeError sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HdLatticeErrorImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Keypair sse_decode_box_autoadd_keypair(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_keypair(deserializer));
  }

  @protected
  ProofInput sse_decode_box_autoadd_proof_input(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_proof_input(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  DilithiumScheme sse_decode_dilithium_scheme(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DilithiumScheme.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Keypair sse_decode_keypair(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_secretKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_scheme = sse_decode_dilithium_scheme(deserializer);
    return Keypair(publicKey: var_publicKey, secretKey: var_secretKey, scheme: var_scheme);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MerkleProcessed sse_decode_merkle_processed(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sortedSiblingsFlat = sse_decode_list_prim_u_8_strict(deserializer);
    var var_positions = sse_decode_list_prim_u_8_strict(deserializer);
    return MerkleProcessed(sortedSiblingsFlat: var_sortedSiblingsFlat, positions: var_positions);
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  U8Array32? sse_decode_opt_u_8_array_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_u_8_array_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProofInput sse_decode_proof_input(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_secret = sse_decode_list_prim_u_8_strict(deserializer);
    var var_transferCount = sse_decode_u_64(deserializer);
    var var_wormholeAddress = sse_decode_list_prim_u_8_strict(deserializer);
    var var_inputAmount = sse_decode_u_32(deserializer);
    var var_blockHash = sse_decode_list_prim_u_8_strict(deserializer);
    var var_blockNumber = sse_decode_u_32(deserializer);
    var var_parentHash = sse_decode_list_prim_u_8_strict(deserializer);
    var var_stateRoot = sse_decode_list_prim_u_8_strict(deserializer);
    var var_extrinsicsRoot = sse_decode_list_prim_u_8_strict(deserializer);
    var var_digest = sse_decode_list_prim_u_8_strict(deserializer);
    var var_zkTreeRoot = sse_decode_list_prim_u_8_strict(deserializer);
    var var_sortedSiblingsFlat = sse_decode_list_prim_u_8_strict(deserializer);
    var var_positions = sse_decode_list_prim_u_8_strict(deserializer);
    var var_exitAccount1 = sse_decode_list_prim_u_8_strict(deserializer);
    var var_outputAmount1 = sse_decode_u_32(deserializer);
    var var_exitAccount2 = sse_decode_list_prim_u_8_strict(deserializer);
    var var_outputAmount2 = sse_decode_u_32(deserializer);
    var var_volumeFeeBps = sse_decode_u_32(deserializer);
    var var_assetId = sse_decode_u_32(deserializer);
    return ProofInput(
      secret: var_secret,
      transferCount: var_transferCount,
      wormholeAddress: var_wormholeAddress,
      inputAmount: var_inputAmount,
      blockHash: var_blockHash,
      blockNumber: var_blockNumber,
      parentHash: var_parentHash,
      stateRoot: var_stateRoot,
      extrinsicsRoot: var_extrinsicsRoot,
      digest: var_digest,
      zkTreeRoot: var_zkTreeRoot,
      sortedSiblingsFlat: var_sortedSiblingsFlat,
      positions: var_positions,
      exitAccount1: var_exitAccount1,
      outputAmount1: var_outputAmount1,
      exitAccount2: var_exitAccount2,
      outputAmount2: var_outputAmount2,
      volumeFeeBps: var_volumeFeeBps,
      assetId: var_assetId,
    );
  }

  @protected
  ProofOutput sse_decode_proof_output(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_proofBytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_nullifier = sse_decode_list_prim_u_8_strict(deserializer);
    return ProofOutput(proofBytes: var_proofBytes, nullifier: var_nullifier);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  U8Array32 sse_decode_u_8_array_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array32(inner);
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WormholeResult sse_decode_wormhole_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_String(deserializer);
    var var_firstHash = sse_decode_list_prim_u_8_strict(deserializer);
    var var_secret = sse_decode_list_prim_u_8_strict(deserializer);
    return WormholeResult(address: var_address, firstHash: var_firstHash, secret: var_secret);
  }

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
    HdLatticeError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize((self as HdLatticeErrorImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHDLatticeError(
    HdLatticeError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize((self as HdLatticeErrorImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_keypair(Keypair self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_keypair(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_proof_input(ProofInput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_proof_input(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_dilithium_scheme(DilithiumScheme self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_keypair(Keypair self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
    sse_encode_list_prim_u_8_strict(self.secretKey, serializer);
    sse_encode_dilithium_scheme(self.scheme, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(List<Uint8List> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_merkle_processed(MerkleProcessed self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.sortedSiblingsFlat, serializer);
    sse_encode_list_prim_u_8_strict(self.positions, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_u_8_array_32(U8Array32? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_u_8_array_32(self, serializer);
    }
  }

  @protected
  void sse_encode_proof_input(ProofInput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.secret, serializer);
    sse_encode_u_64(self.transferCount, serializer);
    sse_encode_list_prim_u_8_strict(self.wormholeAddress, serializer);
    sse_encode_u_32(self.inputAmount, serializer);
    sse_encode_list_prim_u_8_strict(self.blockHash, serializer);
    sse_encode_u_32(self.blockNumber, serializer);
    sse_encode_list_prim_u_8_strict(self.parentHash, serializer);
    sse_encode_list_prim_u_8_strict(self.stateRoot, serializer);
    sse_encode_list_prim_u_8_strict(self.extrinsicsRoot, serializer);
    sse_encode_list_prim_u_8_strict(self.digest, serializer);
    sse_encode_list_prim_u_8_strict(self.zkTreeRoot, serializer);
    sse_encode_list_prim_u_8_strict(self.sortedSiblingsFlat, serializer);
    sse_encode_list_prim_u_8_strict(self.positions, serializer);
    sse_encode_list_prim_u_8_strict(self.exitAccount1, serializer);
    sse_encode_u_32(self.outputAmount1, serializer);
    sse_encode_list_prim_u_8_strict(self.exitAccount2, serializer);
    sse_encode_u_32(self.outputAmount2, serializer);
    sse_encode_u_32(self.volumeFeeBps, serializer);
    sse_encode_u_32(self.assetId, serializer);
  }

  @protected
  void sse_encode_proof_output(ProofOutput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.proofBytes, serializer);
    sse_encode_list_prim_u_8_strict(self.nullifier, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_u_8_array_32(U8Array32 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_wormhole_result(WormholeResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.address, serializer);
    sse_encode_list_prim_u_8_strict(self.firstHash, serializer);
    sse_encode_list_prim_u_8_strict(self.secret, serializer);
  }
}

@sealed
class HdLatticeErrorImpl extends RustOpaque implements HdLatticeError {
  // Not to be used by end users
  HdLatticeErrorImpl.frbInternalDcoDecode(List<dynamic> wire) : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  HdLatticeErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_HdLatticeError,
    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_HdLatticeError,
    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_HdLatticeErrorPtr,
  );
}
