include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120

linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - avoid_print
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_single_quotes
    - use_null_aware_elements

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"
    - "rust_builder/**"
    - build/**
  errors:
    avoid_print: ignore # print is the most reliable way to debug the app
    missing_required_param: error
    missing_return: error
    must_be_immutable: error 