// GENERATED by tool/generate_call_corpus.dart - do not edit by hand.
//
// One synthesized SCALE encoding per call the runtime declares, plus one per
// variant of each enum argument. Regenerate after changing the bindings.
library;

const Map<String, String> callCorpus = {
  'System.remark': '00000c000000',
  'System.set_heap_pages': '00010098f73e5d010000',
  'System.set_code': '00020c000000',
  'System.set_code_without_checks': '00030c000000',
  'System.set_storage': '0004040c0000000c000000',
  'System.kill_storage': '0005040c000000',
  'System.kill_prefix': '00060c00000044420f00',
  'System.remark_with_event': '00070c000000',
  'System.authorize_upgrade': '0009a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'System.authorize_upgrade_without_checks': '000aa0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'System.apply_authorized_upgrade': '000b0c000000',
  'Timestamp.set': '01000b0098f73e5d01',
  'Balances.transfer_allow_death':
      '020000a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a00b0098f73e5d01',
  'Balances.transfer_keep_alive':
      '020300a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a00b0098f73e5d01',
  'Balances.transfer_all': '020400a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a001',
  'Balances.burn': '020a0b0098f73e5d0101',
  'Preimage.note_preimage': '07000c000000',
  'Preimage.unnote_preimage': '0701a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'Preimage.request_preimage': '0702a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'Preimage.unrequest_preimage': '0703a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'Preimage.ensure_updated': '070404a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'Utility.batch_all': '090204000000',
  'ReversibleTransfers.set_high_security':
      '0b000043420f00a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1',
  'ReversibleTransfers.set_high_security [delay=Timestamp]':
      '0b00010098f73e5d010000a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1',
  'ReversibleTransfers.cancel': '0b01a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'ReversibleTransfers.execute_transfer': '0b02a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'ReversibleTransfers.schedule_transfer':
      '0b0300a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a00098f73e5d0100000000000000000000',
  'ReversibleTransfers.schedule_transfer_with_delay':
      '0b0400a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a00098f73e5d01000000000000000000000045420f00',
  'ReversibleTransfers.schedule_transfer_with_delay [delay=Timestamp]':
      '0b0400a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a00098f73e5d0100000000000000000000010098f73e5d010000',
  'ReversibleTransfers.recover_funds': '0b07a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'TechCollective.add_member': '0d0000a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'TechCollective.promote_member': '0d0100a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'TechCollective.demote_member': '0d0200a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'TechCollective.remove_member': '0d0300a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a09210',
  'TechCollective.vote': '0d0443420f0001',
  'TechCollective.cleanup_poll': '0d0543420f0044420f00',
  'TechCollective.exchange_member':
      '0d0600a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a000a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1',
  'TechReferenda.submit': '0e00000000a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a10045420f00',
  'TechReferenda.submit [proposal=Inline]': '0e000000010c0000000045420f00',
  'TechReferenda.submit [proposal=Lookup]':
      '0e00000002a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a144420f000045420f00',
  'TechReferenda.submit [enactment_moment=After]':
      '0e00000000a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a10145420f00',
  'TechReferenda.place_decision_deposit': '0e0143420f00',
  'TechReferenda.refund_decision_deposit': '0e0243420f00',
  'TechReferenda.cancel': '0e0343420f00',
  'TechReferenda.kill': '0e0443420f00',
  'TechReferenda.nudge_referendum': '0e0543420f00',
  'TechReferenda.one_fewer_deciding': '0e069210',
  'TechReferenda.refund_submission_deposit': '0e0743420f00',
  'TechReferenda.set_metadata': '0e0843420f0000',
  'TechReferenda.set_metadata [maybe_hash=Some]':
      '0e0843420f0001a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1',
  'TreasuryPallet.set_treasury_account': '0f00a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'Multisig.create_multisig':
      '130004a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a044420f000098f73e5d010000',
  'Multisig.propose': '1301a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a00c00000045420f00',
  'Multisig.approve': '1302a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a044420f000c000000',
  'Multisig.cancel': '1303a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a044420f00',
  'Multisig.remove_expired': '1304a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a044420f00',
  'Multisig.claim_deposits': '1305a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'Multisig.execute': '1306a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a044420f00000000',
  'Multisig.execute [call=Timestamp]':
      '1306a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a044420f00000000',
  'Multisig.execute [call=Balances]':
      '1306a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a044420f00000000',
  'Multisig.execute [call=Preimage]':
      '1306a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a044420f00000000',
  'Multisig.execute [call=Utility]':
      '1306a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a044420f00000000',
  'Multisig.execute [call=ReversibleTransfers]':
      '1306a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a044420f00000000',
  'Multisig.execute [call=TechCollective]':
      '1306a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a044420f00000000',
  'Multisig.execute [call=TechReferenda]':
      '1306a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a044420f00000000',
  'Multisig.execute [call=TreasuryPallet]':
      '1306a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a044420f00000000',
  'Multisig.execute [call=Multisig]':
      '1306a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a044420f00000000',
  'Multisig.execute [call=Wormhole]':
      '1306a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a044420f00000000',
  'Multisig.execute [call=Vesting]':
      '1306a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a044420f00000000',
  'Wormhole.verify_private_batch': '14020c000000',
  'Wormhole.verify_public_batch': '14030c000000',
  'Vesting.claim': '16000098f73e5d010000',
  'Vesting.create_schedule':
      '1601a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a00098f73e5d0100000098f73e5d0100000098f73e5d0100000098f73e5d0100000000000000000000',
  'Vesting.end_schedule': '16020098f73e5d010000',
  'Vesting.retarget_schedule': '16030098f73e5d010000a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1',
};

/// Encodings naming an address form this runtime cannot resolve, which both
/// wallets refuse rather than display.
const Map<String, String> refusedCallCorpus = {
  'Balances.transfer_allow_death [dest=Index]': '0200010b0098f73e5d01',
  'Balances.transfer_allow_death [dest=Raw]': '0200020c0000000b0098f73e5d01',
  'Balances.transfer_allow_death [dest=Address32]':
      '020003a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a00b0098f73e5d01',
  'Balances.transfer_allow_death [dest=Address20]': '020004a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a00b0098f73e5d01',
  'Balances.transfer_keep_alive [dest=Index]': '0203010b0098f73e5d01',
  'Balances.transfer_keep_alive [dest=Raw]': '0203020c0000000b0098f73e5d01',
  'Balances.transfer_keep_alive [dest=Address32]':
      '020303a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a00b0098f73e5d01',
  'Balances.transfer_keep_alive [dest=Address20]': '020304a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a00b0098f73e5d01',
  'Balances.transfer_all [dest=Index]': '02040101',
  'Balances.transfer_all [dest=Raw]': '0204020c00000001',
  'Balances.transfer_all [dest=Address32]': '020403a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a001',
  'Balances.transfer_all [dest=Address20]': '020404a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a001',
  'ReversibleTransfers.schedule_transfer [dest=Index]': '0b03010098f73e5d0100000000000000000000',
  'ReversibleTransfers.schedule_transfer [dest=Raw]': '0b03020c0000000098f73e5d0100000000000000000000',
  'ReversibleTransfers.schedule_transfer [dest=Address32]':
      '0b0303a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a00098f73e5d0100000000000000000000',
  'ReversibleTransfers.schedule_transfer [dest=Address20]':
      '0b0304a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a00098f73e5d0100000000000000000000',
  'ReversibleTransfers.schedule_transfer_with_delay [dest=Index]': '0b04010098f73e5d01000000000000000000000045420f00',
  'ReversibleTransfers.schedule_transfer_with_delay [dest=Raw]':
      '0b04020c0000000098f73e5d01000000000000000000000045420f00',
  'ReversibleTransfers.schedule_transfer_with_delay [dest=Address32]':
      '0b0403a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a00098f73e5d01000000000000000000000045420f00',
  'ReversibleTransfers.schedule_transfer_with_delay [dest=Address20]':
      '0b0404a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a00098f73e5d01000000000000000000000045420f00',
  'TechCollective.add_member [who=Index]': '0d0001',
  'TechCollective.add_member [who=Raw]': '0d00020c000000',
  'TechCollective.add_member [who=Address32]': '0d0003a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'TechCollective.add_member [who=Address20]': '0d0004a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'TechCollective.promote_member [who=Index]': '0d0101',
  'TechCollective.promote_member [who=Raw]': '0d01020c000000',
  'TechCollective.promote_member [who=Address32]':
      '0d0103a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'TechCollective.promote_member [who=Address20]': '0d0104a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'TechCollective.demote_member [who=Index]': '0d0201',
  'TechCollective.demote_member [who=Raw]': '0d02020c000000',
  'TechCollective.demote_member [who=Address32]':
      '0d0203a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'TechCollective.demote_member [who=Address20]': '0d0204a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0',
  'TechCollective.remove_member [who=Index]': '0d03019210',
  'TechCollective.remove_member [who=Raw]': '0d03020c0000009210',
  'TechCollective.remove_member [who=Address32]':
      '0d0303a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a09210',
  'TechCollective.remove_member [who=Address20]': '0d0304a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a09210',
  'TechCollective.exchange_member [who=Index]':
      '0d060100a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1',
  'TechCollective.exchange_member [who=Raw]':
      '0d06020c00000000a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1',
  'TechCollective.exchange_member [who=Address32]':
      '0d0603a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a000a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1',
  'TechCollective.exchange_member [who=Address20]':
      '0d0604a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a000a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1',
  'TechCollective.exchange_member [new_who=Index]':
      '0d0600a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a001',
  'TechCollective.exchange_member [new_who=Raw]':
      '0d0600a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0020c000000',
  'TechCollective.exchange_member [new_who=Address32]':
      '0d0600a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a003a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1',
  'TechCollective.exchange_member [new_who=Address20]':
      '0d0600a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a004a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1',
};
